# frozen_string_literal: true

# ApplicationUrlsHelper generated by rockstart:frontend_helpers
module ApplicationUrlsHelper
  def url_for_authentication
    root_url # TODO: Provide url for authentication page
  end

  def url_for_landing_page
    root_url # TODO: Provide url for landing page
  end

  def url_for_user_dashboard
    root_url # TODO: Provide url for user dashboard link
  end
end

RSpec.configure do |config|
  config.include ApplicationUrlsHelper
end
